### ISSUE TITLE
custom.yaml improvements

### ISSUE THREAD

**Issue by ZeTopHat** [ZeTopHat/suse-vagrant-labs#4]
I think there's a lot we could add to the custom.yaml. The question though, is what should be in the custom.yaml vs what should be in the global.yaml or lab.yaml, etc.
I thought some that could be added were "bridgename" and "primarysubnet"

**Comment by ZeTopHat** [comment]
Latest commit adjusted the deployment to be a custom.yaml variable rather than separate Vagrantfiles.

**Comment by ZeTopHat** [comment]
Looks like the latest version of the custom.yaml structure is:

```
---
wheredir:
deployment:
extra:
libvirt:
  cpus:
  memory:
  machine_virtual_size:
network:
  bridgename:
  nameserver:
  primarysubnet:
  secondarysubnet:
```

We also have a templated version in the vagrantfiles/ directory with explanations of each of the variables.

I'm going to go ahead and close this for now, since it's a pretty general/vague issue. If there's something in particular we'd like to add later then we can always open up a new issue.
